### ISSUE TITLE
돈스타브 게임을 만든다면 자기 분야의 어떤 기술이 필요한가?

### ISSUE THREAD

**Issue by Moses-Yu** [Moses-Yu/MakingGames#3]

**Comment by Moses-Yu** [comment]
[돈스타브 기능.pdf](https://github.com/Moses-Yu/MakingGames/files/11157984/default.pdf)

**Comment by SeuliI** [comment]
![Image](https://github.com/Moses-Yu/MakingGames/assets/59537819/d8813ae0-2ba0-4fe1-8596-0a94b5066d05)

**Comment by wlgns1471** [comment]
![Image](https://github.com/Moses-Yu/MakingGames/assets/128370955/48fcc392-a9ec-44f7-b762-acfa7f565b0b)

**Comment by Moses-Yu** [comment]
제출 완료
